core/urls.py
from django.urls import path, include

from . import views
from stores import views as viewsStor


app_name = 'core'

urlpatterns = [
    path('', views.index, name='my_home'),
    path('collection/', viewsStor.collection_items, name='collections' ),
    path('hok/', views.hok, name='hok'),



]

puddle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('registApp.urls')),
    path('', include('stores.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, documet_root=settings.STATIC_ROOT)

stores/urls.py
from django.urls import path, reverse
from core.views import index
from . import views

urlpatterns = [
    path("", index, name="home"),
    path('cart/',views.cart, name="cart"),
    path('checkout/',views.checkout, name="checkout"),

    path("collection/", views.collection_items, name="collections"),
    path('collection/all/', views.all_collection, name='all_collection'),
    path('collection/all/<str:name>', views.item_product, name='item_product'),

    path("collection/Armani/", views.armani, name='armani_product'),
    path("collection/Armani/<str:name>", views.item_product, name='item_product'),
    path("collection/Astronic/", views.astronic, name='astronic_product'),
    path("collection/Astronic/<str:name>", views.item_product, name='item_product'),
    path("collection/Ballast/", views.ballast, name='ballast_product'),
    path("collection/Ballast/<str:name>", views.item_product, name='item_product'),
    path("collection/Bulova/", views.bulova, name='bulova_product'),
    path("collection/Bulova/<str:name>", views.item_product, name='item_product'),
    path("collection/California/", views.california, name='california_product'),
    path("collection/California/<str:name>", views.item_product, name='item_product'),
    path("collection/Casio/", views.casio, name='casio_product'),
    path("collection/Casio/<str:name>", views.item_product, name='item_product'),
    path("collection/Citizen/", views.citizen, name='citizen_product'),
    path("collection/Citizen/<str:name>", views.item_product, name='item_product'),
    path("collection/G-Shock/", views.g_shock, name='g_shock_product'),
    path("collection/G-Shock/<str:name>", views.item_product, name='item_product'),
    path("collection/Jason-Hyde/", views.jason_hyde, name='jason_hyde_product'),
    path("collection/Jason-Hyde/<str:name>", views.item_product, name='item_product'),
    path("collection/M2Z/", views.m2z, name='m2z_product'),
    path("collection/M2Z/<str:name>", views.item_product, name='item_product'),
    path("collection/Breitling/", views.breitling, name='breitling_product'),
    path("collection/Breitling/<str:name>", views.item_product, name='item_product'),
    path("collection/Timex/", views.timex, name='timex_product'),
    path("collection/Timex/<str:name>", views.item_product, name='item_product'),
    path("collection/Zodiac/", views.zodiac, name='zodiac_product'),
    path("collection/Zodiac/<str:name>", views.item_product, name='item_product'),

    path('collection/all_sale_products/', views.all_sale_products, name='all_sale_products'),
    path('collection/all_sale_products/<str:name>', views.item_product, name='item_product'),
    path("collection/Sale-M/Armani/", views.sale_armani, name='sale_armani'),
    path("collection/Sale-M/Armani/<str:name>", views.item_product, name='item_product'),
    path("collection/Sale-M/California/", views.sale_california, name='sale_california'),
    path("collection/Sale-M/California/<str:name>", views.item_product, name='item_product'),
    path("collection/Sale-M/G-Shock/", views.sale_g_shock, name='sale_g_shock'),
    path("collection/Sale-M/G-Shock/<str:name>", views.item_product, name='item_product'),

    path("collection/Man-ShopByColor/Black/", views.man_black_color, name='black_man_color'),
    path("collection/Man-ShopByColor/Black/<str:name>", views.item_product, name='item_product'),
    path("collection/Man-ShopByColor/Gold/", views.gold_man_color, name='gold_man_color'),
    path("collection/Man-ShopByColor/Gold/<str:name>", views.item_product, name='item_product'),
    path("collection/Man-ShopByColor/Blue/", views.blue_man_color, name='blue_man_color'),
    path("collection/Man-ShopByColor/Blue/<str:name>", views.item_product, name='item_product'),
    path("collection/Man-ShopByColor/Silver/", views.silver_man_color, name='silver_man_color'),
    path("collection/Man-ShopByColor/Silver/<str:name>", views.item_product, name='item_product'),


    path("collection/Women-ShopByColor/Black/", views.black_women_color, name='black_women_color'),
    path("collection/Women-ShopByColor/Black/<str:name>", views.item_product, name='item_product'),
    path("collection/Women-ShopByColor/Silver/", views.silver_women_color, name='silver_women_color'),
    path("collection/Women-ShopByColor/Silver/<str:name>", views.item_product, name='item_product'),
    path("collection/Women-ShopByColor/Blue/", views.blue_women_color, name='blue_women_color'),
    path("collection/Women-ShopByColor/Blue/<str:name>", views.item_product, name='item_product'),
    path("collection/Women-ShopByColor/Gold/", views.gold_women_color, name='gold_women_color'),
    path("collection/Women-ShopByColor/Gold/<str:name>", views.item_product, name='item_product'),
    path("collection/Women-ShopByColor/Colorful/", views.colorful_women_color, name='colorful_women_color'),
    path("collection/Women-ShopByColor/Colorful/<str:name>", views.item_product, name='item_product'),

    path("collection/Sale-W/G-Shock/", views.sale_w_g_shock, name='sale_w_g_shock'),
    path("collection/Sale-W/G-Shock/<str:name>", views.item_product, name='item_product'),
    path("collection/Sale-W/Jason-Hyde/", views.sale_w_jason_hyde, name='sale_w_jason_hyde'),
    path("collection/Sale-W/Jason-Hyde/<str:name>", views.item_product, name='item_product'),
    path("collection/Sale-W/Timex/", views.sale_w_timex, name='sale_w_timex'),
    path("collection/Sale-W/Timex/<str:name>", views.item_product, name='item_product'),


    path('update_item/', views.updateItem, name='update_item'),
    path('process_order/', views.processOrder, name='process_order'),




]

stores/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    username = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.email)

class CollectionItems(models.Model):
    brandName = models.CharField(max_length=200, null=True)
    photo = models.ImageField(null=True, blank=True)

    @property
    def imageURL(self):
        try:
            url = self.photo.url
        except:
            url = ''
        return url



class Sale_Product(models.Model):
    brand_name= models.CharField(max_length=200, null=True)
    name = models.CharField(max_length=200, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    sale_price = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=2)
    digital = models.BooleanField(default=False, null=True, blank=False)
    sex = models.CharField(max_length=20, null=True)
    image = models.ImageField(null=True, blank=True)
    color = models.CharField(max_length=200, null=True)


    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

class Images(models.Model):
    product = models.ForeignKey(Sale_Product, on_delete=models.CASCADE, blank=True, null=True)
    imagesList = models.ImageField(upload_to='pics', null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.product.name)




class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping=True
        return shipping

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total




class OrderItem(models.Model):
    product = models.ForeignKey(Sale_Product, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True,)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        if self.product.sale_price is not None:
            total = self.product.sale_price * self.quantity
        else:
            total = self.product.price * self.quantity
        return total





class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    phoneNumber = models.CharField(max_length=12, null=True)
    address = models.CharField(max_length=200, null=True)
    postalCode = models.CharField(max_length=10, null=True)
    city = models.CharField(max_length=30, null=True)
    date_added = models.DateTimeField(auto_now_add=True)


    def __str(self):
        return self.address

templates/stores/html/all_sale_products.html
{% extends 'core/html/base.html' %}
{% load static %}
{% block htmlhead %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/all_sale_products.css' %}">

    <script type="text/javascript">
        let user = '{{request.user}}'

        function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== ''){
                let cookies = document.cookie.split(";");
                for(let i=0; i<cookies.length; i++){
                    let cookie = cookies[i].trim();

                    if(cookie.substring(0, name.length + 1) === (name + '=')){
                        cookieValue = decodeURIComponent(cookie.substring(name.length+1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        let csrftoken = getToken("csrftoken");

        function getCookie(name){
            let cookieArr = document.cookie.split(";");

            for(let i=0; i<cookieArr.length; i++){
                let cookiePair = cookieArr[i].split("=");

                if(name == cookiePair[0].trim()){
                    return decodeURIComponent(cookiePair[1]);
                }
            }
            return null;
        }

        let cart = JSON.parse(getCookie('cart'))
        if(cart == undefined){
            cart = {}
            console.log('CART was created')
            document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
        }
        console.log('CART:', cart)

    </script>
    <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>

{% endblock htmlhead %}

{% block title %}{%endblock%}


{% block content %}

<section class="container-sale">
    <div class="box-sale">
        <div class="sale-wrapper">
            <div class="home-text">
                <a href="/">Home/</a>
            </div>

            <div class="header-text">
                <span>Sale</span>
            </div>

            <div class="grid-items">
                 {% for sale_product in sale_products %}
                 {% if sale_product.sale_price != null %}
                 <div class="item">

                    <a href="{{sale_product.name}}" class="hover-img">
                        <div class="photo"><img src="{{sale_product.imageURL}}" alt=""></div>

                        <div class="wrapper-box">
                            <div class="box-element product">
                                <div class="watches-name" ><span>{{ sale_product.name }}</span></div>
                                <div class="price">
                                    {% if sale_product.sale_price != null %}
                                    <p class="price-old">$ {{ sale_product.price|floatformat:2 }}</p>
                                    <p class="price-off">$ {{ sale_product.sale_price|floatformat:2}}</p>
                                    {%else%}
                                    <p class="normal-price">$ {{ sale_product.price|floatformat:2}}</p>
                                    {%endif%}

                                </div>
                            </div>
                        </div>
                    </a>
                </div>

                {%endif%}
                {% endfor %}
            </div>
        </div>
    </div>
</section>


{%endblock%}

templates/stores/html/cart.html
{% extends 'core/html/base.html' %}
{% load static %}
{% block htmlhead %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/cart.css' %}">

  <script type="text/javascript">
        let user = '{{request.user}}'

        function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== ''){
                let cookies = document.cookie.split(";");
                for(let i=0; i<cookies.length; i++){
                    let cookie = cookies[i].trim();

                    if(cookie.substring(0, name.length + 1) === (name + '=')){
                        cookieValue = decodeURIComponent(cookie.substring(name.length+1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        let csrftoken = getToken("csrftoken");

        function getCookie(name){
            let cookieArr = document.cookie.split(";");

            for(let i=0; i<cookieArr.length; i++){
                let cookiePair = cookieArr[i].split("=");

                if(name == cookiePair[0].trim()){
                    return decodeURIComponent(cookiePair[1]);
                }
            }
            return null;
        }

        let cart = JSON.parse(getCookie('cart'))
        if(cart == undefined){
            cart = {}
            console.log('CART was created')
            document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
        }
        console.log('CART:', cart)

    </script>
{% endblock htmlhead %}

{% block title %}{%endblock%}


{% block content %}

<section>
    <div class="row">
        <div class="wrapper-container">
            <div class="main-text">
                <span>SHOPPING BAG</span>
            </div>

            <div class="first-box">
                {% for item in items %}
                    <div class="box-element">
                        <div class="img-text-box">
                            <div class="img-box">
                                <img src="{{item.product.imageURL}}" alt="">
                            </div>
                            <div class="text-and-btn">
                                <p>{{item.product.name}}</p>
                                <button class="update-cart" data-product="{{item.product.id}}" data-action="removeAll">Remove</button>
                            </div>
                        </div>

                        <div class="right-side">
                            <div class="quantity" id="quantity-of-watches">
                                <p>{{item.quantity}}</p>
                                <div class="arrows">
                                    <img src="{% static 'phot/arrow_up.svg' %}" alt="arrow_up" data-product="{{item.product.id}}" data-action="add" class=" update-cart">
                                    <img src="{% static 'phot/arrow_down.svg' %}" alt="arrow_down" data-product="{{item.product.id}}" data-action="remove" class=" update-cart">

                                </div>
                            </div>

                            <div class="center-btn">
                                <buttom class="update-cart" data-product="{{item.product.id}}" data-action="removeAll"><span>Remove</span></buttom>
                            </div>

                            <div class="price">
                                <span>${{item.get_total|floatformat:2}}</span>
                            </div>
                        </div>

                    </div>
                {% endfor %}
            </div>


            <div class="second-box">
                <div class="left-side">
                    <div class="subtotal">
                        <span>Subtotal:</span>
                    </div>

                    <div class="all-price">
                        <span>$ {{order.get_cart_total|floatformat:2}}</span>
                    </div>
                </div>

                {% if order.get_cart_total <= 0 %}
                <div class="right-side">
                    <form action="">
                        <button   onclick="">PROCEED TO CHECKOUT</button>
                    </form>
                </div>
                {% else %}
                <div class="right-side">
                    <form action="{% url 'checkout' %}">
                        <button   onclick="">PROCEED TO CHECKOUT</button>
                    </form>
                </div>
                {% endif %}
            </div>
        </div>

    </div>
     <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>

</section>
{%endblock%}

templates/stores/html/checkout_watch.html
{% extends 'core/html/base.html' %}

{% block htmlhead %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/checkout_watch.css' %}">
{% endblock htmlhead %}

{% block title %}{%endblock%}

{% block content %}
    <section>
        <div class="full-screen-img">
            <img src="{% static 'phot/checkout_photo/main-photo.jpg' %}" alt="">
        </div>
        <div class="container">
            <div class="check-out-wrapper">
                <div class="fill-in-form-container">
                    <div class="header-text">
                        <p>Fill in the forms</p>
                    </div>

                    <div class="input-wrapper" id="form-wrapper">
                        <form id="form">
                            {% csrf_token %}
                            <div class="input-forms-container">
                                <div class="input-forms">
                                    <div id="user-info">
                                        <div class="my-form forms">
                                            <input type="text" name="username" placeholder="username" required>
                                        </div>
                                        <div class="my-form forms">
                                            <input type="email" name="email" placeholder="Email" required>
                                        </div>
                                    </div>


                                   <div id="shipping-info">
                                        <div class="my-form forms">
                                            <input type="tel" name="phone_number" placeholder="Phone number" required>
                                        </div>
                                        <div class="my-form forms">
                                            <input type="text" name="address" placeholder="Address" required>
                                        </div>
                                        <div class="city-postcode">
                                            <div class="my-form forms">
                                                <input type="text" name="postalcode" placeholder="Postalcode" required>
                                            </div>
                                            <div class="my-form forms">
                                                <input type="text" name="city" placeholder="City" required>
                                            </div>
                                        </div>
                                   </div>
                                </div>
                            </div>
                            <div class="bottom-of-fill" id="form-btn" >
                                <div class="return-to-cart btn">
                                    <a href="{% url 'cart' %}">< Return to cart</a>
                                </div>

                                <div class="btn-sbm btn">
                                    <input  type="Submit" value="Send">
                                </div>
                            </div>
                        </form>
                    </div>


                    <div class="box-element hidden" id="payment-info">
                        <div class="paypal-container">
                            <small>Paypal Options</small>
                            <div class="paypal-icons">
                                <div id="paypal-button-container" style="max-width:600px; "></div>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="bg-buy-watches">
                    <div class="buy-watches-container">
                        {% for item in items %}
                        <div class="item-container">
                            <div class="img-wrp">
                                <img src="{{item.product.imageURL}}" alt="">
                            </div>

                            <div class="watch-name txt">
                                <span>{{item.product.name}}</span>
                            </div>

                            <div class="price txt">
                                <span>$ {{item.get_total}}</span>
                            </div>

                        </div>
                        {% endfor %}
                        <hr>

                        <div class="sum-of-watches">
                            <div class="total-txt">
                                <span>Total</span>
                            </div>
                            <div class="price">
                                <span>$ {{order.get_cart_total|floatformat:2}}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="https://www.paypal.com/sdk/js?client-id=ARvepQSxxfOfBlMRKOZPTqSltgG1bGFGBrKdkmJIjdW3KVCJONuKRetHcVjBPDUOumFpRR1rJXasK_JX&currency=USD&locale=en_US"></script>

    <script>
        let total = "{{order.get_cart_total}}"
        paypal.Buttons({

            style: {
                color:'blue',
                shape:'rect',
                width: 25,
            },

            createOrder: function(data, actions){
                return actions.order.create({
                    purchase_units : [{
                        amount: {
                            value: parseFloat(total).toFixed(2)
                        }
                    }]
                });
            },

            onApprove: function(data, actions){
                return actions.order.capture().then(function(details){
                    submitFormData()
                });
            }
        }).render('#paypal-button-container')

    </script>

    <script type="text/javascript">
        let shipping = '{{order.shipping}}'





        if(shipping == 'False'){
            document.getElementById("shipping-info").innerHTML = ""
        }

        if(user != 'AnonymousUser'){
            document.getElementById('user-info').innerHTML = ''
        }

        if(shipping == "False" && user != "AnonymousUser"){
            document.getElementById("form-wrapper").classList.add("hidden")
            document.getElementById("payment-info").classList.remove("hidden")
        }

        let form = document.getElementById('form')
        csrftoken = form.getElementsByTagName("input")[0].value
        console.log('Newtoken:', form.getElementsByTagName("input")[0].value)

        form.addEventListener("submit", function(e){
            e.preventDefault()
            console.log("Form submited...")
            document.getElementById('form-btn').classList.add("hidden")
            document.getElementById('payment-info').classList.remove("hidden")
        })



        function submitFormData(){
            console.log("Payment button clicked")

            let userFormData = {
                "username": null,
                "email": null,
                "total":total,
            }

            let shippingInfo = {
                "address": null,
                "phone_number":null,
                "postalcode": null,
                "city":null,
            }

            if(shipping != "False"){
                shippingInfo.address = form.address.value
                shippingInfo.postalcode = form.postalcode.value
                shippingInfo.city = form.city.value
                shippingInfo.phone_number = form.phone_number.value
            }

            if(user == "AnonymousUser"){
                userFormData.username = form.username.value
                userFormData.email = form.email.value

            }

            let url = "/process_order/"
            fetch(url, {
                method:"POST",
                headers:{
                    'Content-Type':'application/json',
                    'X-CSRFToken':csrftoken,
                },

                body:JSON.stringify({'form':userFormData, 'shipping':shippingInfo}),
            })
            .then((response) => response.json())
            .then((data) => {
                console.log('Success:', data);
                alert('Transaction Completed');

                cart = {}
                document.cookie = "cart=" + JSON.stringify(cart) + ";domain=;path=/"


                window.location.href ="{% url 'home' %}"
            })

        }
    </script>

{%endblock%}

templates/stores/html/collection_items.html
{% extends 'core/html/base.html' %}
{% load static %}
{% block htmlhead %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/collections.css' %}">

    <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
{% endblock htmlhead %}

{% block title %}W{%endblock%}
{% block content %}
<section class="container-sale">
    <div class="box-sale">
        <div class="sale-wrapper">
            <div class="home-text">
                <a href="/">Home/</a>
            </div>

            <div class="header-text">
                <span>All brands</span>
            </div>

            <div class="grid-items">
                {% for collection_product in collection_products %}
                 <div class="item">
                    <a href="{{collection_product.brandName}}" class="hover-img">
                        <div class="photo-wrapper">
                            <div class="photo-txt">
                                <div class="photo">
                                   <img src="{{collection_product.imageURL}}" alt="">
                                    <p class="label">{{collection_product.brandName}}</p>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>

{%endblock%}

templates/stores/html/product_item.html
{% extends 'core/html/base.html' %}


{% block htmlhead %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/product_item.css' %}">


     <script type="text/javascript">
        let user = '{{request.user}}'

        function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== ''){
                let cookies = document.cookie.split(";");
                for(let i=0; i<cookies.length; i++){
                    let cookie = cookies[i].trim();

                    if(cookie.substring(0, name.length + 1) === (name + '=')){
                        cookieValue = decodeURIComponent(cookie.substring(name.length+1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        let csrftoken = getToken("csrftoken");

        function getCookie(name){
            let cookieArr = document.cookie.split(";");

            for(let i=0; i<cookieArr.length; i++){
                let cookiePair = cookieArr[i].split("=");

                if(name == cookiePair[0].trim()){
                    return decodeURIComponent(cookiePair[1]);
                }
            }
            return null;
        }

        let cart = JSON.parse(getCookie('cart'))
        if(cart == undefined){
            cart = {}
            console.log('CART was created')
            document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
        }
        console.log('CART:', cart)

    </script>


{% endblock htmlhead %}


{% block content %}
<section class="container-prod">
<div class="container">

        <div class="wrapper-cont">
             <div class="left-side">
                 <div class="column-photo" >
                     {% for i in sale_products.images_set.all %}
                     <div style="cursor:pointer;" class="img-box"> <img class="image" src="/images/{{i.imagesList}}" alt=""></div>
                     {% endfor %}
                 </div>



                <div class="main-photo" >
                    <img id="main-img" src="{{sale_products.imageURL}}" alt="">
    <!--            <img src="{% static 'phot/Rectangle 42.jpg' %}" alt="">-->
                </div>
            </div>

            <div class="right-side">
                <div class="watch-name">
                    <span>{{sale_products.name}}</span>
                </div>
                <div class="price">
                    {% if sale_products.sale_price != null %}
                    <span>$ {{sale_products.sale_price|floatformat:2}}</span>
                    {% else %}
                    <span>$ {{sale_products.price|floatformat:2}}</span>
                    {% endif %}
                </div>
                <div class="waranty">
                    <img src="{% static 'phot/wARRANTY.jpg' %}" alt="">
                </div>

                <div class="btn">
                    <button class="update-cart" data-product="{{sale_products.id}}" data-action="add">Add to Bag</button>
                </div>
            </div>
        </div>

    </div>
</section>
<script>



</script>

<script type="text/javascript" src="{% static 'js/product_det_img.js' %}"></script>
<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
{% endblock %}